name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install jest
      - run: npm run test
  packer-validate:
    name: Packer validate
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Create zip archived artifacts of webapp
        run: zip -r webapp.zip .
      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer
      - name: Packer Init
        run: packer init packer
      - name: Packer validate
        run: packer validate packer